# Generated by Django 5.1.5 on 2025-02-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='drfapp.teachers'),
        ),
        migrations.AlterField(
            model_name='parentpupil',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_relations', to='drfapp.parents', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='pupils',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupil', to='drfapp.classes'),
        ),
    ]
