# Generated by Django 5.1.5 on 2025-02-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0002_alter_classes_teacher_alter_parentpupil_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='drfapp.teachers'),
        ),
    ]
