# Generated by Django 5.1.5 on 2025-02-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0003_alter_classes_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='drfapp.teachers'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
